#!/bin/bash


# Nutzung: vid2mp4                 -> converts all files in the current folder
#          vid2mp4 datei.xyz       -> converts named file only

convert_file() {
  local input="$1"
  local base_name="${input%.*}"
  local extension="${input##*.}"
  local output=""

  
  if ! [ -f "$input" ]; then
    return
  fi

  
  if ! [[ "$extension" =~ ^(mp4|avi|mov|mkv|flv|wmv|webm)$ ]]; then
    echo "⚠️ Überspringe $input: Nicht unterstütztes Videoformat."
    return 1
  fi

  
  if [[ "$extension" == "mp4" ]]; then
    # if Input is mp4 already, we add "_converted" to the filename so we don't override the original
    output="${base_name}_converted.mp4"
  else
    
    output="${base_name}.mp4"
  fi

  echo "🌀 Konvertiere: $input -> $output"
  

ffmpeg -hide_banner -stats -y -i "$input" -c:v libx264 -crf 23 -preset medium -vf "fps=fps=30:round=near" -c:a aac -b:a 192k "$output"

}

if [ -n "$1" ]; then

  convert_file "$1"
else

  for file in *; do
    if [[ -f "$file" && "$file" =~ \.(mp4|avi|mov|mkv|flv|wmv|webm)$ ]]; then
      convert_file "$file"
    fi
  done
fi
